version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: telegram_bot_postgres
    environment:
      POSTGRES_USER: Abdulla
      POSTGRES_PASSWORD: 12332144
      POSTGRES_DB: monitoring_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network # <-- ОДНА СЕТЬ ДЛЯ ВСЕХ
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Abdulla -d monitoring_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: monitoring_db

      DB_USER: Abdulla
      DB_PASSWORD: 12332144
      BOT_TOKEN: ${BOT_TOKEN}
      DEBUG: "True"
    networks:
      - bot_network # <-- ОДНА СЕТЬ ДЛЯ ВСЕХ
    restart: unless-stopped

  updater:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: monitoring_db
      DB_USER: Abdulla
      DB_PASSWORD: 12332144
      BOT_TOKEN: ${BOT_TOKEN}
      DEBUG: "True"
    command: sh -c "while true; do python worker.py; sleep 86400; done"
    restart: always
    networks:
      - bot_network 

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data:
